# netlify.toml (FINAL CORRECTED VERSION)

[build]
  # This tells Netlify your published site is in the "static" folder.
  publish = "static/"

[functions]
  # This tells Netlify where your Python function source files live.
  directory = "netlify/functions/"

# This special table applies settings to ALL functions in the directory.
# The "*" is a wildcard. This is where runtime settings like 'timeout' go.
[functions."*"]
  # Increase timeout for AI calls. The default of 10s is often too short.
  timeout = 25
  # CRITICAL: This tells Netlify to package the entire 'source_material' folder
  # along with every function that gets deployed.
  included_files = ["source_material/**"]
  
# This rule directs all traffic from /api/... to your functions.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
